INSERT INTO users(name, username, email, role) VALUES('User0','UserName1','user2@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User2','UserName3','user4@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User4','UserName5','user6@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User6','UserName7','user8@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User8','UserName9','user10@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User10','UserName11','user12@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User12','UserName13','user14@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User14','UserName15','user16@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User16','UserName17','user18@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User18','UserName19','user20@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User20','UserName21','user22@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User22','UserName23','user24@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User24','UserName25','user26@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User26','UserName27','user28@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User28','UserName29','user30@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User30','UserName31','user32@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User32','UserName33','user34@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User34','UserName35','user36@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User36','UserName37','user38@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User38','UserName39','user40@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User40','UserName41','user42@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User42','UserName43','user44@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User44','UserName45','user46@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User46','UserName47','user48@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User48','UserName49','user50@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User50','UserName51','user52@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User52','UserName53','user54@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User54','UserName55','user56@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User56','UserName57','user58@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User58','UserName59','user60@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User60','UserName61','user62@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User62','UserName63','user64@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User64','UserName65','user66@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User66','UserName67','user68@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User68','UserName69','user70@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User70','UserName71','user72@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User72','UserName73','user74@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User74','UserName75','user76@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User76','UserName77','user78@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User78','UserName79','user80@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User80','UserName81','user82@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User82','UserName83','user84@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User84','UserName85','user86@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User86','UserName87','user88@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User88','UserName89','user90@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User90','UserName91','user92@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User92','UserName93','user94@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User94','UserName95','user96@gmail.com','USER');
INSERT INTO users(name, username, email, role) VALUES('User96','UserName97','user98@gmail.com','ADMIN');
INSERT INTO users(name, username, email, role) VALUES('User98','UserName99','user100@gmail.com','USER');
-- USER WITH DIFFERENT LOCK
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User100','UserName101','user102@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User102','UserName103','user104@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User104','UserName105','user106@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User106','UserName107','user108@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User108','UserName109','user110@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User110','UserName111','user112@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User112','UserName113','user114@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User114','UserName115','user116@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User116','UserName117','user118@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User118','UserName119','user120@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User120','UserName121','user122@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User122','UserName123','user124@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User124','UserName125','user126@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User126','UserName127','user128@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User128','UserName129','user130@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User130','UserName131','user132@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User132','UserName133','user134@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User134','UserName135','user136@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User136','UserName137','user138@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User138','UserName139','user140@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User140','UserName141','user142@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User142','UserName143','user144@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User144','UserName145','user146@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User146','UserName147','user148@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User148','UserName149','user150@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User150','UserName151','user152@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User152','UserName153','user154@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User154','UserName155','user156@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User156','UserName157','user158@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User158','UserName159','user160@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User160','UserName161','user162@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User162','UserName163','user164@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User164','UserName165','user166@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User166','UserName167','user168@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User168','UserName169','user170@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User170','UserName171','user172@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User172','UserName173','user174@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User174','UserName175','user176@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User176','UserName177','user178@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User178','UserName179','user180@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User180','UserName181','user182@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User182','UserName183','user184@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User184','UserName185','user186@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User186','UserName187','user188@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User188','UserName189','user190@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User190','UserName191','user192@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User192','UserName193','user194@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User194','UserName195','user196@gmail.com','USER',false,false);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User196','UserName197','user198@gmail.com','ADMIN',true,true);
INSERT INTO users(name, username, email, role, is_account_non_locked, is_enabled) VALUES('User198','UserName199','user200@gmail.com','USER',false,false);
