INSERT INTO users(name, username, role) VALUES('User0','UserName1','ADMIN');
INSERT INTO users(name, username, role) VALUES('User1','UserName2','USER');
INSERT INTO users(name, username, role) VALUES('User2','UserName3','ADMIN');
INSERT INTO users(name, username, role) VALUES('User3','UserName4','USER');
INSERT INTO users(name, username, role) VALUES('User4','UserName5','ADMIN');
INSERT INTO users(name, username, role) VALUES('User5','UserName6','USER');
INSERT INTO users(name, username, role) VALUES('User6','UserName7','ADMIN');
INSERT INTO users(name, username, role) VALUES('User7','UserName8','USER');
INSERT INTO users(name, username, role) VALUES('User8','UserName9','ADMIN');
INSERT INTO users(name, username, role) VALUES('User9','UserName10','USER');
INSERT INTO users(name, username, role) VALUES('User10','UserName11','ADMIN');
INSERT INTO users(name, username, role) VALUES('User11','UserName12','USER');
INSERT INTO users(name, username, role) VALUES('User12','UserName13','ADMIN');
INSERT INTO users(name, username, role) VALUES('User13','UserName14','USER');
INSERT INTO users(name, username, role) VALUES('User14','UserName15','ADMIN');
INSERT INTO users(name, username, role) VALUES('User15','UserName16','USER');
INSERT INTO users(name, username, role) VALUES('User16','UserName17','ADMIN');
INSERT INTO users(name, username, role) VALUES('User17','UserName18','USER');
INSERT INTO users(name, username, role) VALUES('User18','UserName19','ADMIN');
INSERT INTO users(name, username, role) VALUES('User19','UserName20','USER');
INSERT INTO users(name, username, role) VALUES('User20','UserName21','ADMIN');
INSERT INTO users(name, username, role) VALUES('User21','UserName22','USER');
INSERT INTO users(name, username, role) VALUES('User22','UserName23','ADMIN');
INSERT INTO users(name, username, role) VALUES('User23','UserName24','USER');
INSERT INTO users(name, username, role) VALUES('User24','UserName25','ADMIN');
INSERT INTO users(name, username, role) VALUES('User25','UserName26','USER');
INSERT INTO users(name, username, role) VALUES('User26','UserName27','ADMIN');
INSERT INTO users(name, username, role) VALUES('User27','UserName28','USER');
INSERT INTO users(name, username, role) VALUES('User28','UserName29','ADMIN');
INSERT INTO users(name, username, role) VALUES('User29','UserName30','USER');
INSERT INTO users(name, username, role) VALUES('User30','UserName31','ADMIN');
INSERT INTO users(name, username, role) VALUES('User31','UserName32','USER');
INSERT INTO users(name, username, role) VALUES('User32','UserName33','ADMIN');
INSERT INTO users(name, username, role) VALUES('User33','UserName34','USER');
INSERT INTO users(name, username, role) VALUES('User34','UserName35','ADMIN');
INSERT INTO users(name, username, role) VALUES('User35','UserName36','USER');
INSERT INTO users(name, username, role) VALUES('User36','UserName37','ADMIN');
INSERT INTO users(name, username, role) VALUES('User37','UserName38','USER');
INSERT INTO users(name, username, role) VALUES('User38','UserName39','ADMIN');
INSERT INTO users(name, username, role) VALUES('User39','UserName40','USER');
INSERT INTO users(name, username, role) VALUES('User40','UserName41','ADMIN');
INSERT INTO users(name, username, role) VALUES('User41','UserName42','USER');
INSERT INTO users(name, username, role) VALUES('User42','UserName43','ADMIN');
INSERT INTO users(name, username, role) VALUES('User43','UserName44','USER');
INSERT INTO users(name, username, role) VALUES('User44','UserName45','ADMIN');
INSERT INTO users(name, username, role) VALUES('User45','UserName46','USER');
INSERT INTO users(name, username, role) VALUES('User46','UserName47','ADMIN');
INSERT INTO users(name, username, role) VALUES('User47','UserName48','USER');
INSERT INTO users(name, username, role) VALUES('User48','UserName49','ADMIN');
INSERT INTO users(name, username, role) VALUES('User49','UserName50','USER');
-- USER WITH DIFFERENT LOCK
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User50','UserName51','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User51','UserName52','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User52','UserName53','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User53','UserName54','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User54','UserName55','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User55','UserName56','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User56','UserName57','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User57','UserName58','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User58','UserName59','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User59','UserName60','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User60','UserName61','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User61','UserName62','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User62','UserName63','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User63','UserName64','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User64','UserName65','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User65','UserName66','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User66','UserName67','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User67','UserName68','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User68','UserName69','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User69','UserName70','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User70','UserName71','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User71','UserName72','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User72','UserName73','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User73','UserName74','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User74','UserName75','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User75','UserName76','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User76','UserName77','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User77','UserName78','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User78','UserName79','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User79','UserName80','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User80','UserName81','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User81','UserName82','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User82','UserName83','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User83','UserName84','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User84','UserName85','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User85','UserName86','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User86','UserName87','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User87','UserName88','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User88','UserName89','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User89','UserName90','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User90','UserName91','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User91','UserName92','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User92','UserName93','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User93','UserName94','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User94','UserName95','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User95','UserName96','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User96','UserName97','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User97','UserName98','USER',false,false);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User98','UserName99','ADMIN',true,true);
INSERT INTO users(name, username, role, is_account_non_locked, is_enabled) VALUES('User99','UserName100','USER',false,false);
